connectDev/base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('rooms/',views.get_Rooms),
    path('rooms/<str:index>/',views.get_Room),
]

connectDev/base/urls.py
"""_summary_"""
from django.urls import path

from . import views

urlpatterns = [
    path('',views.home_page,name='home'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_User,name='logout'),
    path('register/',views.register_page,name='register'),
    path('room/<str:index>/',views.room_page,name='room'),
    path('create-room/',views.create_room,name='create-room'),
    path('profile/<str:index>',views.profile_page,name='user-profile'),
    path('update-user/',views.update_user,name='update-user'),
    path('topics/',views.topics_page,name='topics'),
    path('activity/',views.activity_page,name='activity'),
    path('update-room/<str:index>/',views.update_room,name='update-room'),
    path('delete-room/<str:index>/',views.delete_room,name='delete-room'),
    path('delete-message/<str:index>/',views.delete_message,name='delete-message'),
]

 

connectDev/connectDev/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/', include('base.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

connectDev/base/models.py
"""Django Module"""
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True)
    avatar = models.ImageField(default="avatar.svg")
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]


class Topic(models.Model):
    """Model Class for Topic"""

    name = models.CharField(max_length=200)

    class Meta:
        """Meta Class to Change attrubite of the Model Class"""

        ordering = ["name"]

    def __str__(self) -> str:
        return str(self.name)


class Room(models.Model):
    """Model Class for Room"""

    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(
        User(), related_name="participants", blank=True
    )
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta Class to Change attrubite of the Model Class"""

        ordering = ["-updated", "-created"]

    def __str__(self) -> str:
        return str(self.name)


class Message(models.Model):
    """Model Class for Message"""

    user = models.ForeignKey(User(), on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta Class to Change attrubite of the Model Class"""

        ordering = ["-updated", "-created"]

    def __str__(self) -> str:
        return str(self.body)[:50]

connectDev/base/forms.py
from django.forms import ModelForm
from .models import Room, User
from django.contrib.auth.forms import UserCreationForm


class NewUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["name", "username", "email", "password1", "password2"]


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ["name", "description"]

    def __init__(self, *args, **kwargs):
        super(RoomForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs["placeholder"] = "Name"
        self.fields["description"].widget.attrs["placeholder"] = "About the Room"


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["avatar", "name", "username", "email", "bio"]

connectDev/base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializer import Room_Serializer


@api_view(['GET'])
def get_Rooms(request):
    rooms =  Room.objects.all()
    serializer = Room_Serializer(rooms,many=True)
    return Response(serializer.data)


@api_view(['GET'])
def get_Room(request,index):
    room =  Room.objects.get(id=index)
    serializer = Room_Serializer(room,many=False)
    return Response(serializer.data)

connectDev/base/views.py
"""_summary_"""
from urllib.parse import unquote
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RoomForm, UserForm, NewUserCreationForm
from .models import Room, Topic, Message, User

# Create your views here.
def login_page(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        email = request.POST.get("email").lower()
        password = request.POST.get("password")
        try:
            user = User.objects.get(email=email)
        except: # pylint: disable=bare-except
            messages.error(request, "User does not exists")

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user=user)
            return redirect("home")
        else:
            messages.error(request, "Email or Password does not exists")
    context = {"page": page}
    return render(request, "base/login.html", context)


def logout_User(request):
    logout(request)
    return redirect("home")


def register_page(request):
    form = NewUserCreationForm()
    if request.method == "POST":
        form = NewUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "An error occured during regisitration")

    context = {"form": form}
    return render(request, "base/login.html", context)


def home_page(request):
    q = unquote(request.GET.get("q")) if request.GET.get("q") is not None else ""
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) | Q(name__icontains=q) | Q(description__icontains=q)
    )
    recent_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    topics = Topic.objects.all()
    rooms_count = rooms.count()

    context = {
        "rooms": rooms,
        "topics": topics[:5],
        "rooms_count": rooms_count,
        "recent_messages": recent_messages,
    }
    return render(request, "base/home.html", context)


def room_page(request, index):
    room = Room.objects.get(id=index)
    room_messages = room.message_set.all().order_by("-created")  # type: ignore
    participants = room.participants.all()
    if request.method == "POST":
        message = Message.objects.create(
            user=request.user, room=room, body=request.POST.get("body")
        )
        message.save()
        room.participants.add(request.user)
        return redirect("room", index=room.pk)
    context = {
        "room": room,
        "room_messages": room_messages,
        "participants": participants,
    }
    return render(request, "base/room.html", context)


def profile_page(request, index):
    user = User.objects.get(id=index)
    rooms = user.room_set.all()  # type: ignore
    recent_messages = user.message_set.all()  # type: ignore
    topics = Topic.objects.all()
    context = {
        "user": user,
        "rooms": rooms,
        "topics": topics,
        "recent_messages": recent_messages,
    }
    return render(request, "base/profile.html", context)


@login_required(login_url="login")
def create_room(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == "POST":
        form = RoomForm(request.POST)
        topic = Topic.objects.get_or_create(name=request.POST.get("topic"))
        if form.is_valid():
            room = form.save(commit=False)
            room.host = request.user
            room.topic = topic[0]
            room.save()
            return redirect("home")
    context = {"form": form, "type": "Create", "topics": topics}
    return render(request, "base/create-room.html", context)


@login_required(login_url="login")
def update_room(request, index):
    room = Room.objects.get(id=index)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.method == "POST":
        form = RoomForm(request.POST, instance=room)
        topic = Topic.objects.get_or_create(name=request.POST.get("topic"))
        if form.is_valid():
            room = form.save(commit=False)
            room.topic = topic[0]
            room.save()
            return redirect("home")

    context = {"form": form, "type": "Update", "topics": topics, "room": room}
    return render(request, "base/create-room.html", context)


@login_required(login_url="login")
def delete_room(request, index):
    room = Room.objects.get(id=index)
    if request.user != room.host:
        return HttpResponse("Your are not allowed here")
    if request.method == "POST":
        room.delete()
        return redirect("home")

    context = {"obj": "Room"}
    return render(request, "base/delete.html", context)


@login_required(login_url="login")
def delete_message(request, index):
    message = Message.objects.get(id=index)
    if request.user != message.user:
        return HttpResponse("Your are not allowed here")

    if request.method == "POST":
        message.delete()
        return redirect("home")

    context = {"obj": "message"}
    return render(request, "base/delete.html", context)


@login_required(login_url="login")
def update_user(request):
    user = request.user
    form = UserForm(instance=user)
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        form.save()
        return redirect("user-profile", index=request.user.id)
    context = {"form": form}
    return render(request, "base/update-user.html", context)


def topics_page(request):
    q = unquote(request.GET.get("q")) if request.GET.get("q") is not None else ""
    topics = Topic.objects.filter(Q(name__icontains=q))
    context = {"topics": topics}
    return render(request, "base/topics.html", context)


def activity_page(request):
    q = unquote(request.GET.get("q")) if request.GET.get("q") is not None else ""
    recent_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    context = {"recent_messages": recent_messages}
    return render(request, "base/activity.html", context)

connectDev/base/templates/base/activity.html
{% extends 'index.html' %} {% block content %}
    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">
            {% for message in recent_messages %}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                  </div>
                  <p>
                    @{{ message.user }}
                    <span>{{ message.created|timesince}}</span>
                  </p>
                </a>
                {% if user == message.user %}
                <div class="roomListRoom__actions">
                  <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>delete</title>
                      <path
                        d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
                      </path>
                    </svg>
                  </a>
                </div>
                {% endif %}
              </div>
              <div class="activities__boxContent">
                <p>replied to post <a href="{% url 'room' message.room.id %}">"{{ message.room }}"</a></p>
                <div class="activities__boxRoomContent">
                  {{ message }}
                </div>
              </div>
            </div>
            {% endfor %}

            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="profile.html" class="roomListRoom__author">
                  <div class="avatar avatar--small active">
                    <img src="https://randomuser.me/api/portraits/men/13.jpg" />
                  </div>
                  <p>
                    @mr_spshuvo
                    <span>5 days ago</span>
                  </p>
                </a>
                <div class="roomListRoom__actions">
                  <a href="#">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
              </div>
              <div class="activities__boxContent">
                <p>replied to post “<a href="room.html">100 Days of code challenge!</a>”</p>
                <div class="activities__boxRoomContent">
                  I’ll have to try this sometime. Really like this idea. Wanna talk about it? I ‘m....
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

connectDev/base/templates/base/activityComponent.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for message in recent_messages %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" />
        </div>
        <p>
          @{{ message.user }}
          <span>{{ message.created|timesince}}</span>
        </p>
      </a>
      {% if user == message.user %}
      <div class="roomListRoom__actions">
        <a href="{% url 'delete-message' message.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>delete</title>
            <path
              d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
            </path>
          </svg>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="activities__boxContent">
      <p>replied to post <a href="{% url 'room' message.room.id %}">"{{ message.room }}"</a></p>
      <div class="activities__boxRoomContent">
        {{ message }}
      </div>
    </div>
  </div>
  {% endfor %}

</div>

connectDev/base/templates/base/create-room.html
{% extends 'index.html' %}
{% block content %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>{{type}} Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method='POST'>
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Room Name</label>
              {{ form.name }}
            </div>

            <div class="form__group">
              <label for="room_topic">Topic</label>
              <input required type="text" name="topic" value="{{ room.topic.name }}" id="id_topic" list="topic-list">
              <datalist id="topic-list"> 
                <select id="room_topic">
                  {% for topic in topics %}
                    <option value="{{ topic.name }}">{{ topic.name }}</option>
                  {% endfor %}
                </select>
              </datalist>

            </div>


            <div class="form__group">
              <label for="room_about">About</label>
              {{ form.description }}
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">{{type}} Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
  {% endblock content %}

connectDev/base/templates/base/create-room_test.html
{% extends 'index.html' %}

{% block content %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>


{% endblock content %}

connectDev/base/templates/base/delete.html
{% extends 'index.html' %} {% block content %}

<main class="delete-item layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{ request.META.HTTP_REFERER }}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Back</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="#" method="POST">
          <div class="form__group">
            <p>Are you sure you want to delete "{{ obj }}"?</p>
          </div>

          <div class="for__group">
            <input class="btn btn--main" type="submit" value="Confirm" />
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

connectDev/base/templates/base/deleteRoom.html
{% extends "index.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete the <b>{{obj}}</b> ?</p>
        <a href='{{ request.META.HTTP_REFERER }}'>Go back</a>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

connectDev/base/templates/base/home_test.html
{% extends "index.html" %} {% block content %}

<style>
  .home-container {
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
  }
</style>

<div class="home-container">
  <div>
    {% include 'base/topicComponent.html' %}
  </div>

  <div>
    <h5>{{ rooms_count }} rooms available</h5>
    <a href="{% url 'create-room' %}">Create Room</a>

    <div>
      {% include 'base/feedComponent.html' %}
    </div>
  </div>

  <div>
    {% include 'base/activityComponent.html' %}
  </div>
</div>

{% endblock %}

connectDev/base/templates/base/loginForm.html
{% extends 'index.html' %}

{% block content %}
{% if page == 'login' %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Username:</label>
        <input type="text" name="username" placeholder="Username">

        <label for="">Password:</label>
        <input type="password" name="password" placeholder="Password">

        <input type="submit" value="Login">
    </form>

    <p>Haven't signed up yet?</p>
    <a href="{% url 'register' %}">Sign up</a>
</div>
{% else %}
<div>
    <form action="" method="post">
        {% csrf_token %} 
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
    <p>Already signed up yet?</p>
    <a href="{% url 'login' %}">Sign in</a>
</div>
{% endif %}

{% endblock content %}

connectDev/base/templates/base/profile.html
{% extends 'index.html' %} {% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'base/topicComponent.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="https://randomuser.me/api/portraits/men/11.jpg" />
          </div>
        </div>
        <div class="profile__info">
          <h3>User Name</h3>
          <p>@{{ user.username }}</p>
          {% if request.user == user %}
          <a href="{% url 'update-user' %}" class="btn btn--main btn--pill"
            >Edit Profile</a
          >
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>About</h3>
          <p>
            {{ user.bio }}
          </p>
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Study Rooms Hosted by User Name</h2>
        </div>
      </div>
          {% include 'base/feedComponent.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activityComponent.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

connectDev/base/templates/base/profile_test.html
{% extends 'index.html' %}

{% block content %}
<style>
    .profile-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>


<h1>{{ user.username }}</h1>
<div class='profile-container'>
    <div>
        {% include 'base/topicComponent.html' %}
    </div>

    <div>
        {% include 'base/feedComponent.html' %}
    </div>

    <div>
        {% include 'base/activityComponent.html' %}
    </div>
</div>

{% endblock content %}

connectDev/base/templates/base/room.html
{% extends 'index.html' %}
    
     {% block content %}
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Room</h3>
            </div>
            {% if room.host == request.user %}
            <div class="room__topRight">
              <a href="{% url 'update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
            <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
            data-edit-url="profile.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>ellipsis-horizontal</title>
              <path
                d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
            </svg>
          </button> -->
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{ room.name }}</h3>
                <span>{{ room.created|timesince }}</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'user-profile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                  </div>
                  <span>@{{ room.host.username }}</span>
                </a>
              </div>
              {% comment %} <div class="room__details">
                {{ room.description }}
              </div> {% endcomment %}
              <span class="room__topics">{{ room.topic.name }}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in room_messages %}
                        <div class="thread">
                          <div class="thread__top">
                            <div class="thread__author">
                              <a href="{% url 'user-profile' message.user.id %}" class="thread__authorInfo">
                                <div class="avatar avatar--small">
                                  <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                                </div>
                                <span>@{{ message.user.username }}</span>
                              </a>
                              <span class="thread__date">{{ message.created|timesince }}</span>
                            </div>
                            {% if request.user == message.user %}
                            <div class="thread__delete">
                              <a href="{% url 'delete-message' message.id %}">
                              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                <title>remove</title>
                                <path
                                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                ></path>
                              </svg>
                            </a>
                            </div>
                            {% endif %}
                          </div>
                          <div class="thread__details">
                            {{ message.body }}
                          </div>
                        </div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% if request.user.is_authenticated %}
          <div class="room__message">
            <form action="" method='POST'>
              {% csrf_token %}
              <input type="text" name="body" placeholder="Write message here" />
            </form>
          </div>
          {% endif %}

        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>({{ participants.count }} Joined)</span></h3>
          <div class="participants__list scroll">
            {% for user in participants %}
            <a href="{% url 'user-profile' user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="https://randomuser.me/api/portraits/men/37.jpg" />
              </div>
              <p>
                Username
                <span>@{{user.username}}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
    {% endblock content %}